PRINT N'--- ЗАДАНИЕ 1 ---';
SET NOCOUNT ON;
IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'DBO.X_TABLE'))
DROP TABLE X_TABLE;

DECLARE @c int, @flag char = 'r';

-- DDL и DML команды сами начинают транзакцию
SET IMPLICIT_TRANSACTIONS ON;

CREATE TABLE X_TABLE (ID int); 
INSERT INTO X_TABLE VALUES (1), (2), (3);

SET @c = (SELECT COUNT(*) FROM X_TABLE);
PRINT N'Количество строк во временной таблице X_TABLE: ' + CAST(@c AS VARCHAR(2));

IF @flag = 'c' 
    COMMIT;
ELSE 
    ROLLBACK;

SET IMPLICIT_TRANSACTIONS OFF;

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'DBO.X_TABLE')) 
    PRINT N'Результат: таблица X_TABLE есть (Транзакция зафиксирована)';
ELSE 
    PRINT N'Результат: таблицы X_TABLE НЕТ (Сработал ROLLBACK)';
PRINT N'';
GO


PRINT N'--- ЗАДАНИЕ 2 ---';
BEGIN TRY
BEGIN TRAN;
    PRINT N'Транзакция начата.';
    
INSERT INTO AUDITORIUM_TYPE (AUDITORIUM_TYPE, AUDITORIUM_TYPENAME)
VALUES (N'ТЕСТ-1', N'Тестовая аудитория 1');

INSERT INTO AUDITORIUM_TYPE (AUDITORIUM_TYPE, AUDITORIUM_TYPENAME)
VALUES (N'ТЕСТ-1', N'Тестовая аудитория 2 (Дубликат)');

COMMIT TRAN;
PRINT N'Транзакция зафиксирована.';
END TRY
BEGIN CATCH
PRINT N'ОШИБКА: ' + ERROR_MESSAGE();    
    IF @@TRANCOUNT > 0
BEGIN
ROLLBACK TRAN;
PRINT N'Произошел ROLLBACK. Ни одна тестовая запись не была добавлена.';
END
END CATCH;
PRINT N'';
GO


PRINT N'--- ЗАДАНИЕ 3 ---';
DECLARE @point VARCHAR(32);

BEGIN TRY
BEGIN TRAN;

INSERT INTO AUDITORIUM_TYPE (AUDITORIUM_TYPE, AUDITORIUM_TYPENAME) VALUES (N'ТОЧКА-1', N'Тест Точка 1');
SET @point = 'p1'; 
    SAVE TRAN @point;
    PRINT N'Сохранена точка ' + @point;

INSERT INTO AUDITORIUM_TYPE (AUDITORIUM_TYPE, AUDITORIUM_TYPENAME) VALUES (N'ТОЧКА-2', N'Тест Точка 2');
SET @point = 'p2'; 
    SAVE TRAN @point;
    PRINT N'Сохранена точка ' + @point;
--- ошибка
INSERT INTO AUDITORIUM_TYPE (AUDITORIUM_TYPE, AUDITORIUM_TYPENAME) VALUES (N'ТОЧКА-1', N'Ошибка');

COMMIT TRAN;
END TRY
BEGIN CATCH
PRINT N'Ошибка во время транзакции: ' + ERROR_MESSAGE();
    IF @@TRANCOUNT > 0
BEGIN
        PRINT N'Откатываемся к контрольной точке: ' + @point;
ROLLBACK TRAN @point;
COMMIT TRAN; 
END
END CATCH;

--- -мусор
DELETE FROM AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE IN (N'ТОЧКА-1', N'ТОЧКА-2');
PRINT N'';
GO


/*
-- Задание 4.

-- --- B ---
USE Univer;
BEGIN TRAN;
    UPDATE AUDITORIUM SET AUDITORIUM_CAPACITY = 999 WHERE AUDITORIUM = '206-1';
    WAITFOR DELAY '00:00:10'; 
ROLLBACK; 


-- --- A ---
USE Univer;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED; 
BEGIN TRAN;
    SELECT @@SPID AS Session_ID, 'Dirty Read (Uncommitted)' AS Result, AUDITORIUM_CAPACITY 
    FROM AUDITORIUM WHERE AUDITORIUM = '206-1';
COMMIT;
*/


/*
-- --- B---
USE Univer;
BEGIN TRAN;
    UPDATE AUDITORIUM SET AUDITORIUM_CAPACITY = 999 WHERE AUDITORIUM = '206-1';
    WAITFOR DELAY '00:00:10'; 
ROLLBACK; 


-- --- A ---
USE Univer;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED; 
BEGIN TRAN;
    SELECT @@SPID AS Session_ID, 'Read Committed' AS Result, AUDITORIUM_CAPACITY 
    FROM AUDITORIUM WHERE AUDITORIUM = '206-1';
COMMIT;
*/


/*
-- A --
USE Univer;
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
BEGIN TRAN;
    SELECT AUDITORIUM_CAPACITY FROM AUDITORIUM WHERE AUDITORIUM = '206-1';
    WAITFOR DELAY '00:00:10';
    SELECT AUDITORIUM_CAPACITY FROM AUDITORIUM WHERE AUDITORIUM = '206-1';
COMMIT;


-- B --
USE Univer;
BEGIN TRAN;
    UPDATE AUDITORIUM SET AUDITORIUM_CAPACITY = 100 WHERE AUDITORIUM = '206-1';
COMMIT;
*/


/*
-- A --
USE Univer;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
BEGIN TRAN;
    SELECT COUNT(*) AS LB_K_COUNT FROM AUDITORIUM WHERE AUDITORIUM_TYPE = N'ЛБ-К';
    WAITFOR DELAY '00:00:10';
    SELECT COUNT(*) AS LB_K_COUNT FROM AUDITORIUM WHERE AUDITORIUM_TYPE = N'ЛБ-К';
COMMIT;


-- B --
USE Univer;
BEGIN TRAN;
    INSERT INTO AUDITORIUM (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY) 
    VALUES ('999-Ф', 'Фантом', N'ЛБ-К', 15);
COMMIT;
-- потом нужно удалить: DELETE FROM AUDITORIUM WHERE AUDITORIUM = '999-Ф'
*/


PRINT N'--- ЗАДАНИЕ 8 ---';
PRINT N'Начальный уровень @@TRANCOUNT: ' + CAST(@@TRANCOUNT AS VARCHAR(2));

BEGIN TRAN
PRINT N'После BEGIN TRAN (Внешняя) @@TRANCOUNT: ' + CAST(@@TRANCOUNT AS VARCHAR(2));
INSERT INTO AUDITORIUM_TYPE (AUDITORIUM_TYPE, AUDITORIUM_TYPENAME) VALUES (N'ВНЕШ', N'Внешняя');

BEGIN TRAN
PRINT N'После BEGIN TRAN (Внутренняя) @@TRANCOUNT: ' + CAST(@@TRANCOUNT AS VARCHAR(2));
UPDATE AUDITORIUM_TYPE SET AUDITORIUM_TYPENAME = N'Изменено' WHERE AUDITORIUM_TYPE = N'ВНЕШ';

COMMIT;
PRINT N'После COMMIT (Внутренняя) @@TRANCOUNT: ' + CAST(@@TRANCOUNT AS VARCHAR(2));
 
IF @@TRANCOUNT > 0 
    ROLLBACK;

PRINT N'После ROLLBACK (Внешняя) @@TRANCOUNT: ' + CAST(@@TRANCOUNT AS VARCHAR(2));

IF EXISTS(SELECT 1 FROM AUDITORIUM_TYPE WHERE AUDITORIUM_TYPE = N'ВНЕШ')
    PRINT N'Запись осталась.';
ELSE
    PRINT N'Запись не существует, откат прошел полностью.';
GO