SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
FROM AUDITORIUM
         INNER JOIN AUDITORIUM_TYPE ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
WHERE AUDITORIUM_TYPENAME LIKE N'%компьютер%';

-- 3. На основе таблиц PRORGESS, STUDENT, GROUPS, SUBJECT, PULPIT и FACULTY сформировать перечень студентов, получивших экзаменационные оценки от 6 до 8. Результирующий набор должен содержать столбцы: Факультет, Кафедра, Специальность, Дисциплина, Имя Студента, Оценка. В столбце Оценка должны быть записаны экзаменационные оценки прописью: шесть, семь, восемь. 
-- Результат отсортировать в порядке убывания по столбцу PROGRESS.NOTE.
-- Использовать соединение INNER JOIN, предикат BETWEEN и выражение CASE.
SELECT STUDENT.NAME,
       FACULTY.FACULTY_NAME,
       SUBJECT.SUBJECT_NAME,
       PULPIT.PULPIT_NAME,
       CASE PROGRESS.NOTE
           WHEN 6 THEN N'ШЕСТЬ'
           WHEN 7 THEN N'СЕМЬ'
           WHEN 8 THEN N'ВОСЕМЬ'
           END
FROM PROGRESS
         INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT

         FULL JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
         FULL JOIN FACULTY ON GROUPS.FACULTY = FACULTY.FACULTY
         FULL JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
         FULL JOIN PULPIT ON PULPIT.PULPIT = SUBJECT.PULPIT
WHERE PROGRESS.NOTE BETWEEN 6 and 8
ORDER BY PROGRESS.NOTE DESC;

SELECT PULPIT.PULPIT_NAME, isnull(TEACHER.TEACHER_NAME, '***')
FROM PULPIT
         LEFT OUTER JOIN TEACHER ON PULPIT.PULPIT = TEACHER.PULPIT

SELECT P.PULPIT, T.TEACHER_NAME
FROM PULPIT P
         FULL OUTER JOIN TEACHER T ON P.PULPIT = T.PULPIT;

SELECT PULPIT.PULPIT, TEACHER.TEACHER_NAME
FROM TEACHER
         FULL OUTER JOIN PULPIT ON TEACHER.PULPIT = PULPIT.PULPIT;

SELECT *
FROM AUDITORIUM
         CROSS JOIN AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
;