SELECT T.AUDITORIUM_TYPENAME AS [Тип аудитории],
       MAX(A.AUDITORIUM_CAPACITY) AS [Макс. вместимость],
       MIN(A.AUDITORIUM_CAPACITY) AS [Мин. вместимость],
       ROUND(AVG(CAST(A.AUDITORIUM_CAPACITY AS FLOAT)), 2) AS [Средняя вместимость],
       SUM(A.AUDITORIUM_CAPACITY) AS [Суммарная вместимость],
       COUNT(A.AUDITORIUM) AS [Количество аудиторий]
FROM AUDITORIUM A
         INNER JOIN AUDITORIUM_TYPE T ON A.AUDITORIUM_TYPE = T.AUDITORIUM_TYPE
GROUP BY T.AUDITORIUM_TYPENAME;

SELECT
    CASE
        WHEN AUDITORIUM_CAPACITY < 30 THEN N'Маленькая'
        WHEN AUDITORIUM_CAPACITY BETWEEN 30 AND 60 THEN N'Средняя'
        ELSE N'Большая'
        END AS [Группа вместимости],
    COUNT(*) AS [Количество аудиторий]
FROM AUDITORIUM
GROUP BY
    CASE
        WHEN AUDITORIUM_CAPACITY < 30 THEN N'Маленькая'
        WHEN AUDITORIUM_CAPACITY BETWEEN 30 AND 60 THEN N'Средняя'
        ELSE N'Большая'
        END
ORDER BY [Количество аудиторий] DESC;

SELECT T.Оценка, COUNT(*) AS [Количество студентов]
FROM (
         SELECT
             CASE
                 WHEN NOTE BETWEEN 4 AND 10 THEN NOTE
                 ELSE NULL
                 END AS Оценка
         FROM PROGRESS
     ) AS T
WHERE T.Оценка IS NOT NULL
GROUP BY T.Оценка
ORDER BY T.Оценка DESC;

SELECT F.FACULTY_NAME AS [Факультет],
       G.YEAR_FIRST AS [Год поступления],
       ROUND(AVG(CAST(P.NOTE AS FLOAT)), 2) AS [Средняя оценка]
FROM FACULTY F
         INNER JOIN GROUPS G ON F.FACULTY = G.FACULTY
         INNER JOIN STUDENT S ON G.IDGROUP = S.IDGROUP
         INNER JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
GROUP BY F.FACULTY_NAME, G.YEAR_FIRST
ORDER BY [Средняя оценка] DESC;

SELECT FACULTY.FACULTY_NAME AS [Факультет], PROFESSION.PROFESSION_NAME AS [Специальность], GROUPS.YEAR_FIRST AS [Поток],
       ROUND(AVG(CAST(PROGRESS.NOTE AS FLOAT)), 2) AS [Средняя оценка]
FROM PROGRESS
         INNER JOIN SUBJECT ON PROGRESS.SUBJECT = SUBJECT.SUBJECT
         INNER JOIN STUDENT ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
         INNER JOIN GROUPS ON STUDENT.IDGROUP = GROUPS.IDGROUP
         INNER JOIN PROFESSION ON GROUPS.PROFESSION = PROFESSION.PROFESSION
         INNER JOIN FACULTY ON PROFESSION.FACULTY = FACULTY.FACULTY
WHERE PROGRESS.SUBJECT IN (N'ОАиП', N'СУБД')
GROUP BY FACULTY.FACULTY_NAME, PROFESSION.PROFESSION_NAME, GROUPS.YEAR_FIRST
ORDER BY [Средняя оценка] DESC;

SELECT PR.PROFESSION_NAME AS [Специальность],
       P.SUBJECT AS [Код дисциплины],
       ROUND(AVG(CAST(P.NOTE AS FLOAT)), 2) AS [Средняя оценка]
FROM FACULTY F
         INNER JOIN GROUPS G ON F.FACULTY = G.FACULTY
         INNER JOIN PROFESSION PR ON G.PROFESSION = PR.PROFESSION
         INNER JOIN STUDENT S ON G.IDGROUP = S.IDGROUP
         INNER JOIN PROGRESS P ON S.IDSTUDENT = P.IDSTUDENT
WHERE RTRIM(F.FACULTY) = 'ТОВ'
GROUP BY PR.PROFESSION_NAME, P.SUBJECT;

SELECT SUBJECT AS [Дисциплина],
       COUNT(IDSTUDENT) AS [Количество отличников]
FROM PROGRESS
WHERE NOTE IN (8, 9)
GROUP BY SUBJECT
HAVING COUNT(IDSTUDENT) > 0
ORDER BY [Количество отличников] DESC;