SELECT p.PROFESSION_NAME                   AS [Специальность],
       s.SUBJECT_NAME                      AS [Дисциплина],
       AVG(CAST(pr.NOTE AS DECIMAL(5, 2))) AS [Средняя оценка]
FROM PROGRESS pr
         JOIN STUDENT st ON pr.IDSTUDENT = st.IDSTUDENT
         JOIN GROUPS g ON st.IDGROUP = g.IDGROUP
         JOIN PROFESSION p ON g.PROFESSION = p.PROFESSION
         JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE g.FACULTY = N'ИТ'
GROUP BY ROLLUP (p.PROFESSION_NAME, s.SUBJECT_NAME);

SELECT p.PROFESSION_NAME                   AS [Специальность],
       s.SUBJECT_NAME                      AS [Дисциплина],
       AVG(CAST(pr.NOTE AS DECIMAL(5, 2))) AS [Средняя оценка]
FROM PROGRESS pr
         JOIN STUDENT st ON pr.IDSTUDENT = st.IDSTUDENT
         JOIN GROUPS g ON st.IDGROUP = g.IDGROUP
         JOIN PROFESSION p ON g.PROFESSION = p.PROFESSION
         JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE g.FACULTY = N'ИТ'
GROUP BY CUBE (p.PROFESSION_NAME, s.SUBJECT_NAME);

SELECT p.PROFESSION_NAME, s.SUBJECT_NAME, AVG(CAST(pr.NOTE AS DECIMAL(5, 2))) AS AVG_NOTE
FROM PROGRESS pr
         JOIN STUDENT st ON pr.IDSTUDENT = st.IDSTUDENT
         JOIN GROUPS g ON st.IDGROUP = g.IDGROUP
         JOIN PROFESSION p ON g.PROFESSION = p.PROFESSION
         JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE g.FACULTY = N'ТОВ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME
UNION
SELECT p.PROFESSION_NAME, s.SUBJECT_NAME, AVG(CAST(pr.NOTE AS DECIMAL(5, 2))) AS AVG_NOTE
FROM PROGRESS pr
         JOIN STUDENT st ON pr.IDSTUDENT = st.IDSTUDENT
         JOIN GROUPS g ON st.IDGROUP = g.IDGROUP
         JOIN PROFESSION p ON g.PROFESSION = p.PROFESSION
         JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE g.FACULTY = N'ИТ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME;

SELECT p.PROFESSION_NAME, s.SUBJECT_NAME, AVG(CAST(pr.NOTE AS DECIMAL(5, 2))) AS AVG_NOTE
FROM PROGRESS pr
         JOIN STUDENT st ON pr.IDSTUDENT = st.IDSTUDENT
         JOIN GROUPS g ON st.IDGROUP = g.IDGROUP
         JOIN PROFESSION p ON g.PROFESSION = p.PROFESSION
         JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE g.FACULTY = N'ТОВ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME
UNION ALL
SELECT p.PROFESSION_NAME, s.SUBJECT_NAME, AVG(CAST(pr.NOTE AS DECIMAL(5, 2))) AS AVG_NOTE
FROM PROGRESS pr
         JOIN STUDENT st ON pr.IDSTUDENT = st.IDSTUDENT
         JOIN GROUPS g ON st.IDGROUP = g.IDGROUP
         JOIN PROFESSION p ON g.PROFESSION = p.PROFESSION
         JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE g.FACULTY = N'ИТ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME;

SELECT p.PROFESSION_NAME, s.SUBJECT_NAME
FROM PROGRESS pr
         JOIN STUDENT st ON pr.IDSTUDENT = st.IDSTUDENT
         JOIN GROUPS g ON st.IDGROUP = g.IDGROUP
         JOIN PROFESSION p ON g.PROFESSION = p.PROFESSION
         JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE g.FACULTY = N'ТОВ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME
INTERSECT
SELECT p.PROFESSION_NAME, s.SUBJECT_NAME
FROM PROGRESS pr
         JOIN STUDENT st ON pr.IDSTUDENT = st.IDSTUDENT
         JOIN GROUPS g ON st.IDGROUP = g.IDGROUP
         JOIN PROFESSION p ON g.PROFESSION = p.PROFESSION
         JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE g.FACULTY = N'ИТ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME;

SELECT p.PROFESSION_NAME, s.SUBJECT_NAME
FROM PROGRESS pr
         JOIN STUDENT st ON pr.IDSTUDENT = st.IDSTUDENT
         JOIN GROUPS g ON st.IDGROUP = g.IDGROUP
         JOIN PROFESSION p ON g.PROFESSION = p.PROFESSION
         JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE g.FACULTY = N'ТОВ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME
EXCEPT
SELECT p.PROFESSION_NAME, s.SUBJECT_NAME
FROM PROGRESS pr
         JOIN STUDENT st ON pr.IDSTUDENT = st.IDSTUDENT
         JOIN GROUPS g ON st.IDGROUP = g.IDGROUP
         JOIN PROFESSION p ON g.PROFESSION = p.PROFESSION
         JOIN SUBJECT s ON pr.SUBJECT = s.SUBJECT
WHERE g.FACULTY = N'ХТиТ'
GROUP BY p.PROFESSION_NAME, s.SUBJECT_NAME;

SELECT f.FACULTY_NAME     AS [Факультет],
       g.IDGROUP          AS [Группа],
       COUNT(s.IDSTUDENT) AS [Кол-во студентов]
FROM STUDENT s
         JOIN GROUPS g ON s.IDGROUP = g.IDGROUP
         JOIN FACULTY f ON g.FACULTY = f.FACULTY
GROUP BY ROLLUP (f.FACULTY_NAME, g.IDGROUP);


SELECT AUDITORIUM_TYPE          AS [Тип аудитории],
       SUM(AUDITORIUM_CAPACITY) AS [Суммарная вместимость],
       COUNT(*)                 AS [Количество аудиторий]
FROM AUDITORIUM
GROUP BY ROLLUP (AUDITORIUM_TYPE);