<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\ASPA006\DAL_Celebrity\DAL_Celebrity.csproj" />
    <ProjectReference Include="..\..\ASPA006\DAL_Celebrity_MSSQL\DAL_Celebrity_MSSQL.csproj" />
  </ItemGroup>

</Project>
